name: Clang

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo Clang
        uses: SushiKernel/github-repo-action@v3.1
        with:
          owner: MoeKernel
          repository: clang
          branch: main
          access-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Export Variables
        working-directory: ./clang
        run: |
          echo "TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}" >> .env

      - name: Install Depends
        working-directory: ./clang
        run: |
          pip install -r requirements.txt

      - name: Check Clang Update
        id: check-update
        working-directory: ./clang
        run: |
          python3 update.py
        continue-on-error: true

      - name: Create Release to GitHub.
        working-directory: ./clang
        run: |
          python3 create_release.py
